[book]
title = "Bulletproof Rust Web (ฉบับภาษาไทย)"
authors = ["Bastian Gruber"]
language = "th"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/suradet-ps/rust-web-th/tree/main/book/src"
edit-url-template = "https://github.com/suradet-ps/rust-web-th/edit/main/book/{path}"
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
boost-title = 2
boost-hierarchy = 1

[output.html.code.hidelines]
rust = "# "
